### ISSUE TITLE
Inspiration keywords below the search bar

### ISSUE THREAD

**Issue by sandervh14** [transparentdemocracy/website#11]
Add inspiration keyword buttons below the search bar, for user-friendliness.
Similar to https://howtheyvote.eu.

For some visitors the empty search bar will look daunting. Having some inspirational keywords as suggestion would give them an easy start. Once their curiosity is triggered and they saw a demo with the keywords, their inspiration will come.

Three to five keywords could be randomly selected from: Ukraine, Israel, Europe, immigration, jobs, climate, taxes, religion,...

**Comment by idotj** [comment]
Done

**Comment by sandervh14** [comment]
Nice, thanks!! :-)
