### ISSUE TITLE
Sort motions on descending plenary date

### ISSUE THREAD

**Issue by sandervh14** [transparentdemocracy/website#12]
I just noticed on the prototype screenshots the displayed motions start on plenary date in 2022.
It would be nice if the homepage by default displays the motions ordered backwards in time, meaning the first pages shows the most recent motions.

**Comment by idotj** [comment]
I have been testing client-side pagination to get this issue and the solution trough Angular is very resource-intensive. I will suggest to change the approach and do it in another way (it will need backend work but I have no skills).

The current test has the sort working, but you will see that has really poor performance (it needs to map all the motions and sort by date at the client side)

Branch name: [test/sort-motions](https://github.com/transparentdemocracy/website/tree/test/sort-motions)

**Comment by sandervh14** [comment]
OK, I see.
@GuidoDechamps can you add the 2 parameters on the backend? :-)

**Comment by sandervh14** [comment]
Following from https://github.com/transparentdemocracy/website/issues/17#issuecomment-2138330437:

Currently, the implemented sorting on backend is now sorting on political term, plenary date and plenary number (for in case multiple plenaries occurred on the same date), in descending order.

At this time, I can't think of any other sorting that could be relevant.
Unless maybe the same sorting, but in ascending order.
But the same effect can be achieved by clicking the last page in the pagination element on the bottom of the page.

As conclusion: if you agree, I'd close this issue. You already said sorting was slow on frontend, it's now done on backend, and the above reasoning on no other ordering being relevant, makes the http://localhost:8080/motions/?page=1&size=10&sortBy=date&order=desc URL creation not interesting to implement.

I'm sorry for the work you put into it. I wanted to check how much that was, but I see the branch is not available on the github repo. I hope you think this is OK.

**Comment by idotj** [comment]
Yep, I deleted the branch because of high impact in performance and I will discourage to handle the sorting for that amount of data via Frontend.
If sorting will stay as demanded and no option for the user to interact with the order (asc / desc) then no need to add new params.

No problem for me to close the issue
